import { useTheme } from "@/hooks/useTheme";
import { ReportPriority, ReportSummaryResult } from "@/services/aiService";
import { Sparkles } from "lucide-react-native";
import React from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";

interface ReportSummaryCardProps {
  loading: boolean;
  result: ReportSummaryResult | null;
}

const PRIORITY_CONFIG: Record<
  ReportPriority,
  { label: string; bg: string; fg: string }
> = {
  low: { label: "Low Priority", bg: "#D1FAE5", fg: "#059669" },
  medium: { label: "Medium Priority", bg: "#FEF3C7", fg: "#D97706" },
  high: { label: "High Priority", bg: "#FEE2E2", fg: "#DC2626" },
};

export const ReportSummaryCard: React.FC<ReportSummaryCardProps> = ({
  loading,
  result,
}) => {
  const { colors, spacing, typography, borderRadius, shadows } = useTheme();

  const styles = StyleSheet.create({
    card: {
      backgroundColor: colors.surface,
      borderRadius: borderRadius.lg,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.small,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing.md,
    },
    titleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.xs,
    },
    title: {
      fontSize: typography.sizes.xs,
      fontFamily: typography.fonts.bodyMedium,
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    aiBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      backgroundColor: colors.backgroundAlt,
      borderRadius: borderRadius.full,
      paddingHorizontal: spacing.sm,
      paddingVertical: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    aiBadgeText: {
      fontSize: typography.sizes.xs,
      fontFamily: typography.fonts.bodyRegular,
      color: colors.textMuted,
    },
    loadingContainer: {
      alignItems: "center",
      paddingVertical: spacing.md,
    },
    loadingText: {
      fontSize: typography.sizes.sm,
      fontFamily: typography.fonts.bodyRegular,
      color: colors.textMuted,
      marginTop: spacing.sm,
    },
    summaryText: {
      fontSize: typography.sizes.base,
      fontFamily: typography.fonts.bodyRegular,
      color: colors.textPrimary,
      lineHeight: typography.sizes.base * typography.lineHeights.normal,
      marginBottom: spacing.md,
    },
    row: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    rowLabelContainer: {
      minWidth: 72,
    },
    rowLabel: {
      fontSize: typography.sizes.xs,
      fontFamily: typography.fonts.bodyMedium,
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      paddingTop: 2,
    },
    priorityBadge: {
      borderRadius: borderRadius.sm,
      paddingHorizontal: spacing.sm,
      paddingVertical: 3,
      alignSelf: "flex-start",
    },
    priorityBadgeText: {
      fontSize: typography.sizes.xs,
      fontFamily: typography.fonts.bodyMedium,
    },
    actionText: {
      flex: 1,
      fontSize: typography.sizes.sm,
      fontFamily: typography.fonts.bodyMedium,
      color: colors.textPrimary,
      lineHeight: typography.sizes.sm * typography.lineHeights.normal,
    },
  });

  // Silent fallback — render nothing if the call failed and result is null
  // and we are not loading
  if (!loading && result === null) {
    return null;
  }

  const priorityCfg = result ? PRIORITY_CONFIG[result.priority] : null;

  return (
    <View style={styles.card}>
      <View style={styles.headerRow}>
        <View style={styles.titleRow}>
          <Text style={styles.title}>AI Summary</Text>
        </View>
        <View style={styles.aiBadge}>
          <Sparkles size={10} color={colors.textMuted} />
          <Text style={styles.aiBadgeText}>Generated by AI</Text>
        </View>
      </View>

      {loading ? (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={styles.loadingText}>Analysing report...</Text>
        </View>
      ) : result !== null ? (
        <>
          <Text style={styles.summaryText}>{result.summary}</Text>

          <View style={styles.row}>
            <View style={styles.rowLabelContainer}>
              <Text style={styles.rowLabel}>Priority</Text>
            </View>
            {priorityCfg && (
              <View
                style={[
                  styles.priorityBadge,
                  { backgroundColor: priorityCfg.bg },
                ]}
              >
                <Text
                  style={[styles.priorityBadgeText, { color: priorityCfg.fg }]}
                >
                  {priorityCfg.label}
                </Text>
              </View>
            )}
          </View>

          <View style={[styles.row, { marginBottom: 0 }]}>
            <View style={styles.rowLabelContainer}>
              <Text style={styles.rowLabel}>Action</Text>
            </View>
            <Text style={styles.actionText}>{result.recommendedAction}</Text>
          </View>
        </>
      ) : null}
    </View>
  );
};

export default ReportSummaryCard;
